server:
	g++ -std=c++11 Connection.cpp Acceptor.cpp util.cpp server.cpp InetAddress.cpp Socket.cpp Epoll.cpp Server.cpp EventLoop.cpp Channel.cpp -o server && g++ util.cpp client.cpp -o client
clean:
	rm server && rm client



