server:
	g++ -std=c++11 Buffer.cpp Connection.cpp Acceptor.cpp util.cpp server.cpp InetAddress.cpp Socket.cpp Epoll.cpp Server.cpp EventLoop.cpp Channel.cpp -o server && g++ -std=c++11 util.cpp client.cpp Socket.cpp InetAddress.cpp Buffer.cpp -o client
clean:
	rm server && rm client



